name          'chartbeat-varnish'
version       '0.0.2'
source        'https://github.com/chartbeat-labs/puppet-varnish'
author        'chartbeat'
license       'MIT'
summary       'Module to manage the Varnish Web Accelerator'
description   'Varnish module for Puppet'
project_page  'https://github.com/chartbeat-labs/puppet-varnish'

dependency 'puppetlabs/stdlib', '>= 3.0.0'
dependency 'puppetlabs/apt', '>= 1.4.0'
